#!/bin/bash -e

export USER="vscode"

. /lib/lsb/init-functions

NAME=novnc
PIDFILE=/var/run/$NAME.pid
DAEMON=/opt/novnc/utils/novnc_proxy
DAEMON_OPTS="--vnc localhost:5901"

case "$1" in
start)
log_action_begin_msg "starting novnc with ${DAEMON_OPTS}"
start-stop-daemon -u $USER --start --quiet --background --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
;;

stop)
log_action_begin_msg "stopping novnc"
start-stop-daemon -u $USER --stop --quiet --oknodo --pidfile $PIDFILE
;;

restart)
$0 stop
$0 start
;;
esac

exit 0