#!/bin/bash -e

export USER="vscode"

. /lib/lsb/init-functions

NAME=xvfb
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/bin/Xvfb
# will run on display 2
DAEMON_OPTS=":2 -screen 0 1024x768x24 -ac +extension GLX +render -noreset"

case "$1" in
start)
log_action_begin_msg "starting xvfb with ${DAEMON_OPTS}"
start-stop-daemon -u $USER --start --quiet --background --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
;;

stop)
log_action_begin_msg "stopping xvfb"
start-stop-daemon -u $USER --stop --quiet --oknodo --pidfile $PIDFILE
;;

restart)
$0 stop
$0 start
;;
esac

exit 0