import os
import logging
import pytest
import aqt.qt

from test_utils import testing_utils
from test_utils import gui_testing_utils

from hypertts_addon import constants
from hypertts_addon import component_remove_audio
from hypertts_addon import config_models
from hypertts_addon import errors

logger = logging.getLogger(__name__)

# audio filenames: only the hypertts- prefixed ones were generated by HyperTTS
HYPERTTS_SOUND_1 = 'hypertts-1111.mp3'
HYPERTTS_SOUND_2 = 'hypertts-2222.mp3'
HYPERTTS_SOUND_3 = 'hypertts-3333.mp3'
HYPERTTS_SOUND_4 = 'hypertts-4444.mp3'
FOREIGN_SOUND = 'external-recording.mp3'


def build_hypertts_instance_with_audio():
    """
    set up notes covering every case the dialog has to handle:
      note 1: a single hypertts sound tag, nothing else in the field
      note 2: text followed by a hypertts sound tag
      note 3: audio which HyperTTS did not generate
      note 4: hypertts audio in two different fields
      note 5: no audio at all
    """
    config_gen = testing_utils.TestConfigGenerator()
    hypertts_instance = config_gen.build_hypertts_instance_test_servicemanager('default')
    anki_utils = hypertts_instance.anki_utils

    def set_field(note_id, field_name, value):
        anki_utils.get_note_by_id(note_id).field_dict[field_name] = value

    set_field(config_gen.note_id_1, config_gen.field_sound, f'[sound:{HYPERTTS_SOUND_1}]')
    set_field(config_gen.note_id_2, config_gen.field_sound, f'你好 [sound:{HYPERTTS_SOUND_2}]')
    set_field(config_gen.note_id_3, config_gen.field_sound, f'[sound:{FOREIGN_SOUND}]')
    set_field(config_gen.note_id_4, config_gen.field_sound, f'[sound:{HYPERTTS_SOUND_3}]')
    set_field(config_gen.note_id_4, config_gen.field_sound_english, f'[sound:{HYPERTTS_SOUND_4}]')
    set_field(config_gen.note_id_5, config_gen.field_sound, '')

    note_id_list = [config_gen.note_id_1, config_gen.note_id_2, config_gen.note_id_3,
                    config_gen.note_id_4, config_gen.note_id_5]
    return hypertts_instance, config_gen, note_id_list


def build_component(note_id_list, hypertts_instance):
    dialog = gui_testing_utils.build_empty_dialog()
    component = component_remove_audio.ComponentRemoveAudio(hypertts_instance, dialog)
    component.configure_browser(note_id_list)
    component.draw(dialog.getLayout())
    return dialog, component


def get_table_rows(component):
    """(note_id, field_name, before, after) for every row of the preview table"""
    model = component.table_model
    rows = []
    for row in range(model.rowCount()):
        rows.append(tuple(
            model.data(model.index(row, column), aqt.qt.Qt.ItemDataRole.DisplayRole)
            for column in range(model.columnCount())))
    return rows


# preview
# =======

def test_remove_audio_preview_defaults(qtbot):
    hypertts_instance, config_gen, note_id_list = build_hypertts_instance_with_audio()
    dialog, component = build_component(note_id_list, hypertts_instance)

    # all fields, hypertts audio only
    assert component.field_combobox.currentText() == constants.REMOVE_AUDIO_ALL_FIELDS
    assert component.hypertts_only_checkbox.isChecked() == True
    assert component.get_model() == config_models.RemoveAudioConfig(field_name=None,
        hypertts_only=True)

    # the field combo box lists all fields found on the selected notes, sorted
    assert [component.field_combobox.itemText(i) for i in range(component.field_combobox.count())] == \
        [constants.REMOVE_AUDIO_ALL_FIELDS] + sorted(config_gen.all_fields)

    # the note with foreign audio and the note without audio are not listed
    assert get_table_rows(component) == [
        (config_gen.note_id_1, config_gen.field_sound, f'[sound:{HYPERTTS_SOUND_1}]', ''),
        (config_gen.note_id_2, config_gen.field_sound, f'你好 [sound:{HYPERTTS_SOUND_2}]', '你好'),
        (config_gen.note_id_4, config_gen.field_sound, f'[sound:{HYPERTTS_SOUND_3}]', ''),
        (config_gen.note_id_4, config_gen.field_sound_english, f'[sound:{HYPERTTS_SOUND_4}]', ''),
    ]
    assert '4' in component.summary_label.text()
    assert '3' in component.summary_label.text()
    assert component.remove_button.isEnabled() == True


def test_remove_audio_preview_all_audio(qtbot):
    hypertts_instance, config_gen, note_id_list = build_hypertts_instance_with_audio()
    dialog, component = build_component(note_id_list, hypertts_instance)

    # uncheck "only remove audio added by HyperTTS", the foreign audio shows up
    component.hypertts_only_checkbox.setChecked(False)

    assert component.get_model().hypertts_only == False
    assert get_table_rows(component) == [
        (config_gen.note_id_1, config_gen.field_sound, f'[sound:{HYPERTTS_SOUND_1}]', ''),
        (config_gen.note_id_2, config_gen.field_sound, f'你好 [sound:{HYPERTTS_SOUND_2}]', '你好'),
        (config_gen.note_id_3, config_gen.field_sound, f'[sound:{FOREIGN_SOUND}]', ''),
        (config_gen.note_id_4, config_gen.field_sound, f'[sound:{HYPERTTS_SOUND_3}]', ''),
        (config_gen.note_id_4, config_gen.field_sound_english, f'[sound:{HYPERTTS_SOUND_4}]', ''),
    ]


def test_remove_audio_preview_single_field(qtbot):
    hypertts_instance, config_gen, note_id_list = build_hypertts_instance_with_audio()
    dialog, component = build_component(note_id_list, hypertts_instance)

    # restrict to the "Sound English" field
    component.field_combobox.setCurrentText(config_gen.field_sound_english)

    assert component.get_model() == config_models.RemoveAudioConfig(
        field_name=config_gen.field_sound_english, hypertts_only=True)
    assert get_table_rows(component) == [
        (config_gen.note_id_4, config_gen.field_sound_english, f'[sound:{HYPERTTS_SOUND_4}]', ''),
    ]

    # and back to the "Sound" field
    component.field_combobox.setCurrentText(config_gen.field_sound)
    assert get_table_rows(component) == [
        (config_gen.note_id_1, config_gen.field_sound, f'[sound:{HYPERTTS_SOUND_1}]', ''),
        (config_gen.note_id_2, config_gen.field_sound, f'你好 [sound:{HYPERTTS_SOUND_2}]', '你好'),
        (config_gen.note_id_4, config_gen.field_sound, f'[sound:{HYPERTTS_SOUND_3}]', ''),
    ]


def test_remove_audio_nothing_to_remove(qtbot):
    hypertts_instance, config_gen, note_id_list = build_hypertts_instance_with_audio()
    # only select the note which has no audio, and the one with foreign audio
    dialog, component = build_component([config_gen.note_id_3, config_gen.note_id_5],
        hypertts_instance)

    assert get_table_rows(component) == []
    assert component.summary_label.text() == constants.GUI_TEXT_REMOVE_AUDIO_NOTHING_TO_REMOVE
    assert component.remove_button.isEnabled() == False

    # unchecking hypertts_only reveals the foreign audio and re-enables the button
    component.hypertts_only_checkbox.setChecked(False)
    assert len(get_table_rows(component)) == 1
    assert component.remove_button.isEnabled() == True


# applying
# ========

def test_remove_audio_apply(qtbot):
    hypertts_instance, config_gen, note_id_list = build_hypertts_instance_with_audio()
    dialog, component = build_component(note_id_list, hypertts_instance)

    qtbot.mouseClick(component.remove_button, aqt.qt.Qt.MouseButton.LeftButton)

    # the notes were updated
    assert hypertts_instance.anki_utils.get_note_by_id(config_gen.note_id_1).set_values == {
        config_gen.field_sound: ''}
    assert hypertts_instance.anki_utils.get_note_by_id(config_gen.note_id_2).set_values == {
        config_gen.field_sound: '你好'}
    assert hypertts_instance.anki_utils.get_note_by_id(config_gen.note_id_4).set_values == {
        config_gen.field_sound: '',
        config_gen.field_sound_english: ''}
    # the note with foreign audio was left alone
    assert hypertts_instance.anki_utils.get_note_by_id(config_gen.note_id_3).set_values == {}
    assert hypertts_instance.anki_utils.get_note_by_id(config_gen.note_id_5).set_values == {}

    # the operation is undoable, under its own undo entry
    assert hypertts_instance.anki_utils.undo_started == True
    assert hypertts_instance.anki_utils.undo_finished == True
    assert hypertts_instance.anki_utils.undo_entry_name == constants.UNDO_ENTRY_REMOVE_AUDIO

    # the dialog reports what it did and locks the options down
    assert component.applied == True
    assert component.removed_sound_tag_count == 4
    assert component.modified_note_count == 3
    assert 'Removed' in component.summary_label.text()
    assert 'Undo' in component.summary_label.text()
    assert get_table_rows(component) == []
    assert component.remove_button.isEnabled() == False
    assert component.remove_button.text() == 'Done'
    assert component.field_combobox.isEnabled() == False
    assert component.hypertts_only_checkbox.isEnabled() == False
    assert component.cancel_button.text() == 'Close'


def test_remove_audio_apply_single_field_all_audio(qtbot):
    hypertts_instance, config_gen, note_id_list = build_hypertts_instance_with_audio()
    dialog, component = build_component(note_id_list, hypertts_instance)

    component.field_combobox.setCurrentText(config_gen.field_sound)
    component.hypertts_only_checkbox.setChecked(False)

    qtbot.mouseClick(component.remove_button, aqt.qt.Qt.MouseButton.LeftButton)

    assert component.removed_sound_tag_count == 4
    assert component.modified_note_count == 4
    # foreign audio removed too this time
    assert hypertts_instance.anki_utils.get_note_by_id(config_gen.note_id_3).set_values == {
        config_gen.field_sound: ''}
    # the other field of note 4 was not touched
    assert hypertts_instance.anki_utils.get_note_by_id(config_gen.note_id_4).set_values == {
        config_gen.field_sound: ''}


def test_remove_audio_cancel(qtbot):
    hypertts_instance, config_gen, note_id_list = build_hypertts_instance_with_audio()
    dialog, component = build_component(note_id_list, hypertts_instance)

    qtbot.mouseClick(component.cancel_button, aqt.qt.Qt.MouseButton.LeftButton)

    assert dialog.closed == True
    # nothing was modified
    for note_id in note_id_list:
        assert hypertts_instance.anki_utils.get_note_by_id(note_id).set_values == {}
    assert hypertts_instance.anki_utils.undo_started == False


# full workflow through the dialog factory
# ========================================

def test_remove_audio_dialog_workflow(qtbot):
    hypertts_instance, config_gen, note_id_list = build_hypertts_instance_with_audio()

    def dialog_input_sequence(dialog):
        component = dialog.remove_audio_component
        assert dialog.windowTitle() == constants.GUI_REMOVE_AUDIO_DIALOG_TITLE
        assert len(get_table_rows(component)) == 4
        qtbot.mouseClick(component.remove_button, aqt.qt.Qt.MouseButton.LeftButton)
        qtbot.mouseClick(component.cancel_button, aqt.qt.Qt.MouseButton.LeftButton)

    hypertts_instance.anki_utils.dialog_input_fn_map[constants.DIALOG_ID_REMOVE_AUDIO] = \
        dialog_input_sequence
    component = component_remove_audio.create_component_remove_audio_browser(
        hypertts_instance, note_id_list)

    assert component.applied == True
    assert component.removed_sound_tag_count == 4
    assert hypertts_instance.anki_utils.get_note_by_id(config_gen.note_id_1).set_values == {
        config_gen.field_sound: ''}


def test_remove_audio_dialog_no_notes_selected(qtbot):
    hypertts_instance, config_gen, note_id_list = build_hypertts_instance_with_audio()
    with pytest.raises(errors.NoNotesSelected):
        component_remove_audio.create_component_remove_audio_browser(hypertts_instance, [])


def test_remove_audio_manual(qtbot):
    # HYPERTTS_REMOVE_AUDIO_DIALOG_DEBUG=yes pytest tests/test_component_remove_audio.py -k test_remove_audio_manual -s -rPP
    hypertts_instance, config_gen, note_id_list = build_hypertts_instance_with_audio()

    def dialog_input_sequence(dialog):
        if os.environ.get('HYPERTTS_REMOVE_AUDIO_DIALOG_DEBUG', 'no') == 'yes':
            dialog.exec()

    hypertts_instance.anki_utils.dialog_input_fn_map[constants.DIALOG_ID_REMOVE_AUDIO] = \
        dialog_input_sequence
    component_remove_audio.create_component_remove_audio_browser(hypertts_instance, note_id_list)
