#!/usr/bin/env python3

items = [
    # HYPERTTS_EASY_DIALOG_DEBUG=yes pytest --log-cli-level=DEBUG tests/test_components.py -k test_easy_dialog_editor_manual -s -rPP
    {
        'name': 'test easy dialog editor (field text)',
        'command': 'HYPERTTS_EASY_DIALOG_DEBUG=yes pytest --log-cli-level=DEBUG tests/test_component_batch_editor.py -k test_easy_dialog_editor_manual_field_text -s -rPP'
    },
    {
        'name': 'test easy dialog editor (clipboard, selected)',
        'command': 'HYPERTTS_EASY_DIALOG_DEBUG=yes pytest --log-cli-level=DEBUG tests/test_component_batch_editor.py -k test_easy_dialog_editor_manual_clipboard_selected -s -rPP'
    },    
    {
        'name': 'unit test test_voice_selection_easy_single_1',
        'command': 'pytest --log-cli-level=DEBUG tests/test_components.py -k test_voice_selection_easy_single_1 -vv'
    },        
    {
        'name': 'test voice selection manual',
        'command': 'HYPERTTS_VOICE_SELECTION_DIALOG_DEBUG=yes pytest tests/test_components.py -k test_voice_selection_manual'
    },
    {
        'name': 'test preferences manual',
        'command': 'HYPERTTS_PREFERENCES_DIALOG_DEBUG=yes pytest tests/test_components.py -k test_preferences_manual'
    },
    {
        'name': 'test preset mapping rules manual',
        'command': 'HYPERTTS_DIALOG_DEBUG=yes pytest --log-cli-level=DEBUG tests/test_component_presetmappingrules.py -k test_component_preset_mapping_rules_manual_4'
    },    


]

print(f"""<openbox_pipe_menu>""")
for item in items:
    print(f"""
    <item label="{item['name']}">
        <action name="Execute">
        <command>/home/luc/code/python/anki-hyper-tts/scripts/run_hypertts_manual_test {item['command']} -s -rPP</command>
        </action>
    </item>
    """)
print(f"""</openbox_pipe_menu>""")